import {
  DEFAULT_MESSAGES,
  PRODUCT_MESSAGES,
  USER_MESSAGES,
} from '@/common/constants/message.constant';

export const MESSAGE_MAP = {
  '/users': {
    200: USER_MESSAGES.REQUEST_SUCCESS,
    201: USER_MESSAGES.CREATED_SUCCESS,
  },
  '/users/register': {
    201: USER_MESSAGES.REGISTER_SUCCESS,
  },
  '/auth/login': {
    200: USER_MESSAGES.LOGIN_SUCCESS,
  },
  '/images': {
    201: PRODUCT_MESSAGES.IMAGE_UPLOAD_SUCCESS,
  },
  '/products': {
    200: PRODUCT_MESSAGES.REQUEST_SUCCESS,
    201: PRODUCT_MESSAGES.CREATED_SUCCESS,
  },

  default: {
    200: DEFAULT_MESSAGES.REQUEST_SUCCESS,
    201: DEFAULT_MESSAGES.RESOURCE_CREATED,
    204: DEFAULT_MESSAGES.RESOURCE_DELETED,
    default: DEFAULT_MESSAGES.REQUEST_PROCESSED,
  },
};
